kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: active-job-cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./
        containerPath: /application
    extraPortMappings:
      - containerPort: 30335
        hostPort: 3000